### ISSUE TITLE
feat: expose port and network for bitcoin testcontainer

### ISSUE THREAD

**Issue by theborakompanioni** [theborakompanioni/bitcoin-spring-boot-starter#56]
Expose and use `port` and `network` in `BitcoindContainerProperties`.

- [ ] Replace properties in **all** config files
e.g.
```yaml
org.tbk.bitcoin.jsonrpc:
  network: regtest
  rpchost: http://localhost
  rpcport: 18443
  rpcuser: ${org.tbk.spring.testcontainer.bitcoind.rpcuser}
  rpcpassword: ${org.tbk.spring.testcontainer.bitcoind.rpcpassword}
```
to
```yaml
org.tbk.bitcoin.jsonrpc:
  network:  ${org.tbk.spring.testcontainer.bitcoind.network}
  rpchost: http://localhost
  rpcport: ${org.tbk.spring.testcontainer.bitcoind.rpcport}
  rpcuser: ${org.tbk.spring.testcontainer.bitcoind.rpcuser}
  rpcpassword: ${org.tbk.spring.testcontainer.bitcoind.rpcpassword}
```
